dekorate:
  kubernetes:
    name: helloworld-demo
    replicas: "1"
    deployment-strategy: RollingUpdate
    rolling-update:
      maxSurge: "100%"
      maxUnavailable: "0%"
    liveness-probe:
      http-action-path: /actuator/health/liveness
      initial-delay-seconds: "30"
      period-seconds: "10"
    readiness-probe:
      http-action-path: /actuator/health/readiness
      initial-delay-seconds: "30"
      period-seconds: "10"
    service-account: microservice
    image-pull-policy: Always
    env-vars:
      - name: SPRING_PROFILES_ACTIVE
        value: dev
    expose: false
  docker:
    image: ghcr.io/kubeopsskills/helloworld-demo
  # docker:
  #   image: gcr.io/kubernetes-the-hardway-267516/helloworld-demo
  options:
    output-path: ../../manifests